EXEC usp_Outbound_ASM_NAMMCA

@Format_Name='NAMMCA' ,@Health_Plan_Name='Anthem Blue Cross'

/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 1000 [Inbound_ASM_Id]
      ,[File_LINE_NUM]
      ,[DTL]
      ,[TPID]
      ,[REFERENCE_NUMBER]
      ,[Emerald_Barcode_ID]
      ,[PLAN_MEMBER_ID]
      ,[MEMBER_SSN]
      ,[Member_Last_Name]
      ,[Member_Middle_Initial]
      ,[Member_First_Name]
      ,[MEMBER_DATE_OF_BIRTH]
      ,[Member_Gender_Code]
      ,[MEMBER_MEDICARE_STATE_CODE]
      ,[HICN]
      ,[Claim_Date_of_Service_From]
      ,[Claim_Date_of_Service_Thru]
      ,[Bill_Type]
      ,[Discharge_Status]
      ,[Provider_ID]
      ,[Provider_NPIN]
      ,[Provider_Type]
      ,[Facility_Name]
      ,[Provider_Last_Name]
      ,[Provider_First_Name]
      ,[CMS_SPECIALTY_TYPE]
      ,[Provider_Federal_Tax_ID]
      ,[Provider_Group_Name]
      ,[Provider_Group_NPI]
      ,[CPT_Code]
      ,[Revenue_Code]
      ,[SERVICE_DETAIL_DOS_FROM]
      ,[SERVICE_DETAIL_DOS_THRU]
      ,[POS]
      ,[ICD_Indicator]
      ,[RISK_ASSESSMENT_CODE]
      ,[Chart_Type]
      ,[CHART_BARCODE]
      ,[CHART_ENCOUNTER_KEY]
      ,[Health_Plan_Name]
      ,[CHART_DX_Key]
      ,[Group_Name]
      ,[Contract_ID]
      ,[MemberAddress1]
      ,[MemberAddress2]
      ,[MemberCity]
      ,[MemberState]
      ,[MemberZIP]
      ,[Filler_6]
      ,[DIAG_CODE_1]
      ,[DIAG_CODE_2]
      ,[DIAG_CODE_3]
      ,[DIAG_CODE_4]
      ,[DIAG_CODE_5]
      ,[DIAG_CODE_6]
      ,[DIAG_CODE_7]
      ,[DIAG_CODE_8]
      ,[DIAG_CODE_9]
      ,[DIAG_CODE_10]
      ,[DIAG_CODE_11]
      ,[DIAG_CODE_12]
      ,[DIAG_CODE_13]
      ,[DIAG_CODE_14]
      ,[DIAG_CODE_15]
      ,[DIAG_CODE_16]
      ,[DIAG_CODE_17]
      ,[DIAG_CODE_18]
      ,[DIAG_CODE_19]
      ,[DIAG_CODE_20]
      ,[DIAG_CODE_21]
      ,[DIAG_CODE_22]
      ,[DIAG_CODE_23]
      ,[DIAG_CODE_24]
      ,[DIAG_CODE_25]
      ,[DIAG_CODE_26]
      ,[DIAG_CODE_27]
      ,[DIAG_CODE_28]
      ,[DIAG_CODE_29]
      ,[DIAG_CODE_30]
      ,[DIAG_CODE_31]
      ,[DIAG_CODE_32]
      ,[DIAG_CODE_33]
      ,[DIAG_CODE_34]
      ,[DIAG_CODE_35]
      ,[DIAG_CODE_36]
      ,[DIAG_CODE_37]
      ,[DIAG_CODE_38]
      ,[DIAG_CODE_39]
      ,[DIAG_CODE_40]
      ,[Reference_Number_Resub]
      ,[Error_Codes]
      ,[FileName]
      ,[ImportTimeStamp]
      ,[LCDO_Name]
      ,[Submission_Status_Flag]
      ,[Source]
      ,[Project]
      ,[Incremental_Status]
      ,[Priority]
      ,[Source_File_Name]
      ,[Status]
      ,[Status_Description]
      ,[Created_Date]
      ,[ProviderSpecialtyCode]
      ,[HCC]
      ,[Corrected_Provider_NPIN]
      ,[Corrected_Provider_Federal_Tax_ID]
  FROM [Optum_Cleanup].[dbo].[Inbound_ASM]




/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 1000 [Detail_ID]
      ,[Client_Config_ID]
      ,[HEALTH_PLAN_ID]
      ,[MBR_ID]
      ,[MBR_LAST_NAME]
      ,[MBR_FIRST_NAME]
      ,[MBR_DOB]
      ,[MBR_GENDER]
      ,[SUBSCRIBER_ID]
      ,[MED_GID]
      ,[MED_GRP_NAME]
      ,[MKT]
      ,[DOS_FROM]
      ,[DOS_THRU]
      ,[ICD_Code]
      ,[HCC_Code]
      ,[PROV_LAST_NAME]
      ,[PROV_FIRST_NAME]
      ,[PROV_ID_INTERNAL]
      ,[ALT_PROV_ID]
      ,[SOURCE]
      ,[EXPORT_DATE]
      ,[TERTIARY]
      ,[SEQ_PROV_ID]
      ,[PRIMARY_COMMENT]
      ,[SECONDARY_COMMENT]
      ,[ADDTITIONAL_COMMENTS]
      ,[PAGE_NO]
      ,[Chart_Type]
      ,[Emerald_Barcode_ID]
      ,[Health_Plan_Name]
      ,[LCDO_Name]
      ,[CHART_ID]
      ,[Created_Date]
  FROM [Optum_Cleanup].[dbo].[OutPut_ASM_NAMMCA_Detail]



Select *
   FROM [Optum_Cleanup].[dbo].[Inbound_ASM]
   Where [Provider_Federal_Tax_ID] is NULL and [Corrected_Provider_Federal_Tax_ID] is NULL

=if(Q2!="NULL",Q2,if(S2!="NULL",S2,if(U2!="NULL",U2,if(W2!="NULL",W2,if(X2!="NULL",X2,"NULL")))))